import NavGroup from "@/components/NavGroup";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavItem from "@/components/NavItem";
import "./globals.css";
import { cn } from "@/lib/utils";
import URLBar from "@/components/URLBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <div className="p-8 basis-82 h-screen overflow-y-auto">
            <h1 className="text-xl font-light">
              <strong className="font-semibold">App</strong> router
            </h1>
            <div className="py-4"></div>
            <NavGroup title="Routing">
              <NavItem href="/dynamic-routes">Dynamic routes</NavItem>
              <NavItem href="/catch-all">Catch all routes</NavItem>
              <NavItem href="/parallel">Parallel routes</NavItem>
              <NavItem href="/intercepting">Intercepting routes</NavItem>
            </NavGroup>
            <div className="py-4"></div>
            <NavGroup title="Layouts">
              <NavItem href="/nested-layouts">Nested layouts</NavItem>
              <NavItem href="/route-groups">
                Route groups (grouped layouts)
              </NavItem>
            </NavGroup>
            <div className="py-4"></div>
            <NavGroup title="Files & states">
              <NavItem href="/loading">Loading</NavItem>
              <NavItem href="/error">Error</NavItem>
              <NavItem href="/not-found">Not found</NavItem>
            </NavGroup>
            <div className="py-4"></div>
            <NavGroup title="Rendering & Data fetching">
              <NavItem href="/streaming">Streaming</NavItem>
              <NavItem href="/ssg">Static data (SSG)</NavItem>
              <NavItem href="/ssr">Dynamic data (SSR)</NavItem>
              <NavItem href="/isr">Incremental Static Regeneration</NavItem>
            </NavGroup>
            <div className="py-4"></div>
            <NavGroup title="Mutation">
              <NavItem href="">Route handler</NavItem>
              <NavItem href="">Server action</NavItem>
            </NavGroup>
            <div className="py-4"></div>
            <NavGroup title="Other">
              <NavItem href="">Client context</NavItem>
              <NavItem href="">Pagination</NavItem>
              <NavItem href="">Stripe integration</NavItem>
            </NavGroup>
          </div>
          <div className="flex-1 h-screen overflow-y-auto p-32">
            <div className="border p-4 rounded-md">
              <URLBar />
            </div>
            <div className="py-2"></div>
            <div className="border p-4 rounded-md">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
