import NavGroup from "@/components/NavGroup";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavItem from "@/components/NavItem";
import "./globals.css";
import { cn } from "@/lib/utils";
import URLBar from "@/components/URLBar";
import Menu from "./Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="lg:flex">
          <div className="fixed bg-white lg:relative top-0 left-0 right-0 px-8 z-30 lg:basis-82 lg:h-screen h-14 lg:overflow-y-auto flex justify-between items-center lg:py-8 lg:items-start lg:flex-col lg:justify-normal">
            <h1 className="text-xl font-light">
              <strong className="font-semibold">App</strong> router
            </h1>
            <div className="py-4"></div>
            <Menu />
          </div>
          <div className="flex-1 lg:h-screen lg:overflow-y-auto lg:p-32 pt-32 p-8">
            <div className="border p-4 rounded-md">
              <URLBar />
            </div>
            <div className="py-2"></div>
            <div className="border p-4 rounded-md">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
